version: 2.0

workflows:
  master-release:
    name: Master Release Build
    max_build_duration: 60
    environment:
      groups:
        - app_center_credentials
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS release
        script: flutter build ios --release
      - name: Build Android release (AAB)
        script: flutter build appbundle --release
      - name: Publish to App Center (iOS)
        script: |
          npm install -g appcenter-cli
          appcenter distribute release \
              --group Collaborators \
              --file build/ios/iphoneos/Runner.ipa \
              --release-notes 'Master branch release' \
              --app $ORGANIZATION_NAME/$APP_CENTER_APP_NAME_IOS \
              --token $APP_CENTER_TOKEN \
              --quiet
      - name: Publish to App Center (Android)
        script: |
          npm install -g appcenter-cli
          appcenter distribute release \
              --group Collaborators \
              --file build/app/outputs/bundle/release/app-release.aab \
              --release-notes 'Master branch release' \
              --app $ORGANIZATION_NAME/$APP_CENTER_APP_NAME_ANDROID \
              --token $APP_CENTER_TOKEN \
              --quiet

  develop-debug:
    name: Develop Debug Build
    max_build_duration: 60
    environment:
      groups:
        - app_center_credentials
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS debug
        script: flutter build ios --debug
      - name: Build Android debug (APK)
        script: flutter build apk --debug
      - name: Publish to App Center (iOS Debug)
        script: |
          npm install -g appcenter-cli
          appcenter distribute release \
              --group Collaborators \
              --file build/ios/iphoneos/Runner.ipa \
              --release-notes 'Develop branch debug build' \
              --app $ORGANIZATION_NAME/$APP_CENTER_APP_NAME_IOS \
              --token $APP_CENTER_TOKEN \
              --quiet
      - name: Publish to App Center (Android Debug)
        script: |
          npm install -g appcenter-cli
          appcenter distribute release \
              --group Collaborators \
              --file build/app/outputs/flutter-apk/app-debug.apk \
              --release-notes 'Develop branch debug build' \
              --app $ORGANIZATION_NAME/$APP_CENTER_APP_NAME_ANDROID \
              --token $APP_CENTER_TOKEN \
              --quiet

  pull-request-debug:
    name: Pull Request Debug Build
    max_build_duration: 60
    environment:
      groups:
        - app_center_credentials
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS debug
        script: flutter build ios --debug
      - name: Build Android debug (APK)
        script: flutter build apk --debug
