name: Android Debug Build

on:
  push:
    branches:
      - develop
    paths:
      - '**.dart'
      - 'pubspec.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --debug

      - name: List Contents of Working Directory
        run: ls -la

      - name: Upload APK to Slack
        run: |
          VERSION="${{ github.run_number }}"
          curl -F file=@./build/app/outputs/flutter-apk/app-debug.apk \
               -F "initial_comment=Debug-build version $VERSION" \
               -F channels=random \
               -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
               https://slack.com/api/files.upload
