name: Flutter Android Debug Build and Slack Notification

on:
  push:
    branches:
      - develop
    paths:
      - '**.dart'
      - 'pubspec.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --debug
      - run: ls -la ./app/build/outputs/apk/debug/

      # Apk upload
      - name: Upload APK to Slack
        run: |
          VERSION="${{ github.run_number }}"
          curl -F file=@./app/build/outputs/apk/debug/app-debug.apk \
               -F "initial_comment=Debug-build version $VERSION" \
               -F channels=random \
               -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
               https://slack.com/api/files.upload
