name: iOS Debug Build

on:
  push:
    branches:
      - develop
    paths:
      - '**.dart'
      - 'pubspec.yaml'
      - '**.yml'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Flutter Setup
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign
      - name: Generate IPA
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/ios/iphoneos/Runner.xcarchive -exportOptionsPlist $PWD/ExportOptions.plist -exportPath $PWD/build/app-debug.ipa      
      
      - name: Upload iOS App to Slack
        run: |
          VERSION="${{ github.run_number }}"
          curl -F file =@./build/app-debug.ipa \
               -F "initial_comment=IOS::Debug-build version $VERSION" \
               -F channels=random \
               -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
               https://slack.com/api/files.upload
