name: Flutter Pull Request 

on:
  pull_request:
    paths:
      - '**.dart'
      - 'pubspec.yaml'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'

    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-

    - name: Print Working Directory
      run: pwd

    # Run Flutter Doctor for Debugging
    - name: Flutter Doctor
      run: flutter doctor -v  

    - name: Flutter Clean
      run: flutter clean

    - name: Flutter Analyze
      run: flutter analyze

    - name: Flutter Test
      run: flutter test

    - name: Flutter Build APK
      if: matrix.os == 'ubuntu-latest'
      run: flutter build apk --debug

    - name: Flutter Build iOS
      if: matrix.os == 'macOS-latest'
      run: |
        sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
        flutter build ios --debug --no-codesign
